# Generated by Django 6.0.5 on 2026-08-24 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_report_municipality'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportstatushistory',
            name='previous_status',
            field=models.CharField(blank=True, choices=[('pendiente_validacion', 'Pendiente de validación'), ('reportado', 'Reportado'), ('en_proceso', 'En proceso'), ('resuelto', 'Resuelto'), ('cancelado', 'Cancelado'), ('archivado', 'Archivado')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='reportstatushistory',
            name='reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
