# Generated by Django 6.0.5 on 2026-09-07 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.models import OuterRef, Subquery


def backfill_like_dates(apps, schema_editor):
    """Fecha los me gusta anteriores a que ``Like`` tuviera ``created_at``.

    Se usa la creación de su reporte, que es la única fecha que se sabe cierta y
    la más conservadora para el archivado por inactividad de US-031: nunca
    adelanta el reloj de un reporte.
    """
    Like = apps.get_model("reports", "Like")
    Report = apps.get_model("reports", "Report")
    # Subconsulta y no ``F("report__created_at")``: un ``update()`` no puede
    # referirse a un campo del otro lado de un join.
    Like.objects.filter(created_at__isnull=True).update(
        created_at=Subquery(
            Report.objects.filter(pk=OuterRef("report_id")).values("created_at")[:1],
        ),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('municipalities', '0004_operationalarea'),
        ('reports', '0006_report_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='archival_warning_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='area_assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='operational_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='municipalities.operationalarea'),
        ),
        migrations.CreateModel(
            name='OfficialResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='official_responses', to=settings.AUTH_USER_MODEL)),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='official_responses', to='municipalities.municipality')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='official_responses', to='reports.report')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportAreaAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments_to', to='municipalities.operationalarea')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('previous_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignments_from', to='municipalities.operationalarea')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area_assignments', to='reports.report')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RunPython(
            backfill_like_dates,
            migrations.RunPython.noop,
            elidable=True,
        ),
    ]
