# Generated by Django 6.0.5 on 2026-09-08 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.models import Q


def backfill_transition_origins(apps, schema_editor):
    """Le pone origen a los asientos escritos antes de que el campo existiera.

    Sin esto, el panel dejaría de reconocer como validación en terreno todo lo
    decidido hasta acá: el detalle pasó a identificarla por el origen y no por
    la forma de la transición, porque desde US-040 esa forma la comparten dos
    caminos distintos.

    Las reglas salen de qué transiciones existían antes de esta migración, que
    es lo único que puede haber en la tabla:

    - Saliendo de *Pendiente de validación* con responsable: lo decidió un
      validador en terreno; era el único camino.
    - Saliendo de *Pendiente de validación* sin responsable: el archivado
      automático por inactividad de US-031.
    - Todo lo demás: una persona ejerciendo su rol desde el panel.
    """
    History = apps.get_model("reports", "ReportStatusHistory")
    pending = "pendiente_validacion"

    History.objects.filter(previous_status=pending, changed_by__isnull=False).update(
        origin="validacion_terreno",
    )
    History.objects.filter(previous_status=pending, changed_by__isnull=True).update(
        origin="archivado_inactividad",
    )
    History.objects.filter(~Q(previous_status=pending), origin="").update(
        origin="manual",
    )


class Migration(migrations.Migration):

    dependencies = [
        ('municipalities', '0004_operationalarea'),
        ('reports', '0007_like_created_at_report_archival_warning_sent_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='appeal_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='objection_warning_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportstatushistory',
            name='confirmation_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportstatushistory',
            name='origin',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('pendiente_validacion', 'Pendiente de validación'), ('reportado', 'Reportado'), ('en_proceso', 'En proceso'), ('resuelto_pendiente_confirmacion', 'Resuelto pendiente de confirmación'), ('resuelto', 'Resuelto'), ('cancelado', 'Cancelado'), ('archivado', 'Archivado')], default='pendiente_validacion', max_length=40),
        ),
        migrations.AlterField(
            model_name='reportstatushistory',
            name='previous_status',
            field=models.CharField(blank=True, choices=[('pendiente_validacion', 'Pendiente de validación'), ('reportado', 'Reportado'), ('en_proceso', 'En proceso'), ('resuelto_pendiente_confirmacion', 'Resuelto pendiente de confirmación'), ('resuelto', 'Resuelto'), ('cancelado', 'Cancelado'), ('archivado', 'Archivado')], default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='reportstatushistory',
            name='status',
            field=models.CharField(choices=[('pendiente_validacion', 'Pendiente de validación'), ('reportado', 'Reportado'), ('en_proceso', 'En proceso'), ('resuelto_pendiente_confirmacion', 'Resuelto pendiente de confirmación'), ('resuelto', 'Resuelto'), ('cancelado', 'Cancelado'), ('archivado', 'Archivado')], max_length=40),
        ),
        migrations.CreateModel(
            name='ResolutionEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='resolutions/%Y/%m/')),
                ('description', models.TextField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operational_area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resolution_evidences', to='municipalities.operationalarea')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolution_evidences', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resolution_evidences', to='reports.report')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResolutionAppeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('photo', models.ImageField(upload_to='appeals/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resolution_appeals', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resolution_appeals', to='reports.report')),
                ('evidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appeals', to='reports.resolutionevidence')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
            migrations.RunPython(
            backfill_transition_origins,
            migrations.RunPython.noop,
            elidable=True,
        ),
    ]
