# Generated by Django 6.0.5 on 2026-06-10 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ciudadano', 'Ciudadano'), ('municipal', 'Municipal')], default='ciudadano', max_length=20),
        ),
    ]
