# Generated by Django 6.0.5 on 2026-08-24 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('municipalities', '0001_initial'),
        ('users', '0003_user_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='municipality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='municipalities.municipality', verbose_name='municipality'),
        ),
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='El usuario todavía usa la contraseña temporal del alta.', verbose_name='must change password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ciudadano', 'Ciudadano'), ('admin_plataforma', 'Administrador de la plataforma'), ('agente_municipal', 'Agente municipal'), ('validador', 'Validador')], default='ciudadano', max_length=20),
        ),
    ]
