# Generated by Django 6.0.5 on 2026-08-24 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_migrate_municipal_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_validator_active',
            field=models.BooleanField(default=True, help_text='Solo aplica a usuarios con rol Validador.', verbose_name='validator active'),
        ),
    ]
