# Generated by Django 6.0.5 on 2026-09-07 20:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('municipalities', '0004_operationalarea'),
        ('users', '0007_rename_is_validator_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='operational_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operators', to='municipalities.operationalarea', verbose_name='operational area'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=30, validators=[django.core.validators.RegexValidator(message='El teléfono solo puede tener números, espacios, guiones, paréntesis y un prefijo «+» inicial.', regex='^\\+?[0-9][0-9\\s\\-()]{5,29}$')], verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_work_account_active',
            field=models.BooleanField(default=True, help_text='Solo aplica a validadores, operarios y agentes municipales.', verbose_name='work account active'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ciudadano', 'Ciudadano'), ('admin_plataforma', 'Administrador de la plataforma'), ('agente_municipal', 'Agente municipal'), ('validador', 'Validador'), ('operario', 'Operario')], default='ciudadano', max_length=20),
        ),
    ]
