# Generated by Django 6.0.5 on 2026-08-24 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('locality', models.CharField(max_length=120, verbose_name='locality')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'municipality',
                'verbose_name_plural': 'municipalities',
                'ordering': ['name', 'locality'],
                'constraints': [models.UniqueConstraint(fields=('name', 'locality'), name='unique_municipality_name_locality')],
            },
        ),
    ]
