# Generated by Django 6.0.5 on 2026-09-07 20:26

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('municipalities', '0003_coverage_boundary'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationalArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='contact email')),
                ('contact_phone', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='El teléfono solo puede tener números, espacios, guiones, paréntesis y un prefijo «+» inicial.', regex='^\\+?[0-9][0-9\\s\\-()]{5,29}$')], verbose_name='contact phone')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operational_areas', to='municipalities.municipality', verbose_name='municipality')),
            ],
            options={
                'verbose_name': 'operational area',
                'verbose_name_plural': 'operational areas',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('municipality'), name='unique_operational_area_name_per_municipality', violation_error_message='Ya existe un área operativa con ese nombre en tu municipalidad.')],
            },
        ),
    ]
