# Generated by Django 6.0.5 on 2026-08-24 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_status_change_detail'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('nuevo_comentario', 'Nuevo comentario'), ('cambio_estado', 'Cambio de estado'), ('nuevo_like', 'Nuevo like')], max_length=30)),
                ('enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['kind'],
                'constraints': [models.UniqueConstraint(fields=('user', 'kind'), name='unique_notification_preference')],
            },
        ),
    ]
