# Generated by Django 6.0.5 on 2026-09-07 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('nuevo_comentario', 'Nuevo comentario'), ('cambio_estado', 'Cambio de estado'), ('nuevo_like', 'Nuevo like'), ('respuesta_oficial', 'Respuesta oficial'), ('proximo_archivado', 'Reporte por archivarse')], max_length=30),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='kind',
            field=models.CharField(choices=[('nuevo_comentario', 'Nuevo comentario'), ('cambio_estado', 'Cambio de estado'), ('nuevo_like', 'Nuevo like'), ('respuesta_oficial', 'Respuesta oficial'), ('proximo_archivado', 'Reporte por archivarse')], max_length=30),
        ),
    ]
