# Generated by Django 6.0.5 on 2026-09-08 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notification_kind_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('nuevo_comentario', 'Nuevo comentario'), ('cambio_estado', 'Cambio de estado'), ('nuevo_like', 'Nuevo like'), ('respuesta_oficial', 'Respuesta oficial'), ('proximo_archivado', 'Reporte por archivarse'), ('proxima_confirmacion', 'Cierre por confirmarse'), ('apelacion_cierre', 'Cierre apelado')], max_length=30),
        ),
        migrations.AlterField(
            model_name='notification',
            name='new_status',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='notification',
            name='previous_status',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='kind',
            field=models.CharField(choices=[('nuevo_comentario', 'Nuevo comentario'), ('cambio_estado', 'Cambio de estado'), ('nuevo_like', 'Nuevo like'), ('respuesta_oficial', 'Respuesta oficial'), ('proximo_archivado', 'Reporte por archivarse'), ('proxima_confirmacion', 'Cierre por confirmarse'), ('apelacion_cierre', 'Cierre apelado')], max_length=30),
        ),
    ]
